# Generated by Django 4.2.13 on 2024-06-07 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_trade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='brokerage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trade_images/'),
        ),
        migrations.AddField(
            model_name='trade',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
